# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formulario Digilenciado',
                'verbose_name_plural': 'Formularios Digilenciados',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Cerrada',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banco_encuesta.Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta Cerrada',
                'verbose_name_plural': 'Respuestas Cerradas',
            },
            bases=('banco_encuesta.respuesta',),
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banco_encuesta.Respuesta')),
                ('respuesta', models.TextField(verbose_name='\xbfOtro? \xbfCual?')),
            ],
            options={
                'verbose_name': 'Respuesta Otro',
                'verbose_name_plural': 'Respuestas Otro',
            },
            bases=('banco_encuesta.respuesta',),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_encuesta.FormularioD'),
        ),
    ]
