# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco_encuesta', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariod',
            name='diligenciador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Diligenciador'),
        ),
        migrations.AddField(
            model_name='formulariod',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Instrumento'),
        ),
        migrations.AddField(
            model_name='otros',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Cerrada'),
        ),
        migrations.AddField(
            model_name='cerrada',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Cerrada'),
        ),
        migrations.AddField(
            model_name='cerrada',
            name='respuestas',
            field=models.ManyToManyField(to='encuesta.Opcion'),
        ),
    ]
