# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_encuesta', '0002_auto_20170516_0403'),
        ('usuarios', '0001_initial'),
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariod',
            name='diligenciador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Diligenciador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariod',
            name='instrumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuesta.Instrumento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otros',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuesta.Cerrada'),
            preserve_default=False,
        ),
    ]
