# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170516_0407'),
        ('encuesta', '0001_initial'),
        ('banco_encuesta', '0003_auto_20170516_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('diligenciadores', models.ManyToManyField(to='usuarios.Diligenciador')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.Instrumento')),
            ],
            options={
                'verbose_name': 'Asignaci\xf3n de Encuesta',
                'verbose_name_plural': 'Asignaciones de Encuesta',
            },
        ),
    ]
