# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170529_2014'),
        ('banco_encuesta', '0005_asignarencuesta_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCompletado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_encuesta.AsignarEncuesta')),
                ('diligenciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Diligenciador')),
            ],
            options={
                'verbose_name': 'Encuesta completada',
                'verbose_name_plural': 'Encuestass de Encuesta',
            },
        ),
    ]
