# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_encuesta', '0006_formulariocompletado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariocompletado',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='formulariocompletado',
            name='diligenciador',
        ),
        migrations.AddField(
            model_name='formulariod',
            name='asignacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banco_encuesta.AsignarEncuesta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormularioCompletado',
        ),
    ]
