# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_encuesta', '0008_remove_formulariod_instrumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignarencuesta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formulariod',
            options={'verbose_name': 'Formulario Digilenciado', 'verbose_name_plural': 'Formularios AsignarEncuestaEgresado'},
        ),
        migrations.RemoveField(
            model_name='asignarencuesta',
            name='diligenciadores',
        ),
        migrations.RemoveField(
            model_name='asignarencuesta',
            name='grupo',
        ),
    ]
