# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_encuesta', '0010_asignarencuestaegresado_asignarencuestaempleador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignarencuestaegresado',
            options={'verbose_name': 'Asignaci\xf3n encuesta a egresado', 'verbose_name_plural': 'Asignaciones a egresados'},
        ),
        migrations.AlterModelOptions(
            name='asignarencuestaempleador',
            options={'verbose_name': 'Asignaci\xf3n encuesta a empleador', 'verbose_name_plural': 'Asignaciones  a empleadores'},
        ),
        migrations.AlterModelOptions(
            name='formulariod',
            options={'verbose_name': 'Formulario Digilenciado', 'verbose_name_plural': 'Formularios Digilenciados'},
        ),
    ]
