# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_encuesta', '0012_auto_20170702_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignarencuestaegresado',
            name='egresados',
            field=models.ManyToManyField(blank=True, to='usuarios.Egresado'),
        ),
    ]
