# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170516_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de egresados',
                'verbose_name_plural': 'Grupos de Egresados',
            },
        ),
        migrations.AddField(
            model_name='egresado',
            name='graduado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupoperiodo',
            name='egresados',
            field=models.ManyToManyField(to='usuarios.Egresado'),
        ),
    ]
