# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20170619_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleador',
            name='cargo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
