# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20170810_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diligenciador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
