# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20170829_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
