# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20170829_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleador',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
