# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20180820_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diligenciador',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='graduado',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True),
        ),
    ]
