# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
