# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_remove_pregunta_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='estado',
        ),
    ]
