# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_remove_pregunta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='tipo',
            field=models.BooleanField(choices=[(False, 'Egresado'), (True, 'Empleador')], default=False),
        ),
    ]
