# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0005_instrumento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.TextField(),
        ),
    ]
