# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_auto_20170620_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='preguntas',
        ),
        migrations.AddField(
            model_name='cerrada',
            name='instrumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuesta.Instrumento'),
            preserve_default=False,
        ),
    ]
