# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-20 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_auto_20180820_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.ManyToManyField(to='encuesta.Opcion'),
        ),
    ]
